// Generated by Xata Codegen 0.27.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "users",
    columns: [
      { name: "userid", type: "string" },
      { name: "username", type: "string" },
      { name: "completed", type: "int" },
      { name: "total-product", type: "int" },
      { name: "email", type: "string" },
      { name: "fullname", type: "string" },
    ],
  },
  {
    name: "products",
    columns: [
      { name: "platform", type: "string" },
      { name: "productName", type: "string" },
      { name: "price", type: "string" },
      { name: "url", type: "string" },
      { name: "productID", type: "string" },
      { name: "userid", type: "string" },
    ],
  },
  {
    name: "usage",
    columns: [
      { name: "userid", type: "string" },
      { name: "username", type: "string" },
      { name: "usage", type: "int" },
      { name: "limit", type: "int" },
    ],
  },
  {
    name: "expense",
    columns: [
      { name: "userid", type: "string" },
      { name: "title", type: "string" },
      { name: "category", type: "string" },
      { name: "code", type: "string" },
      { name: "price", type: "string" },
      { name: "date", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type Products = InferredTypes["products"];
export type ProductsRecord = Products & XataRecord;

export type Usage = InferredTypes["usage"];
export type UsageRecord = Usage & XataRecord;

export type Expense = InferredTypes["expense"];
export type ExpenseRecord = Expense & XataRecord;

export type DatabaseSchema = {
  users: UsersRecord;
  products: ProductsRecord;
  usage: UsageRecord;
  expense: ExpenseRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL: "https://Timi-s-workspace-eouder.us-east-1.xata.sh/db/wishme",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
